// Sentences for the "เรียงประโยค & ไวยากรณ์" game.
// Schema: {en, th, lv, cat, note}. Vocabulary stays within common Oxford 3000 words.
// Categories also feed the mini-games (continuation / cloze). Loaded before app.js.
const SENTENCES = [
  // ── การเดินทางและท่องเที่ยว (travel) ──
  {"en":"I go to the airport.","th":"ฉันไปสนามบิน","lv":"A1","cat":"travel","note":"present simple บอกการกระทำ. 'go to' = ไปยัง, ตามด้วยสถานที่."},
  {"en":"We travel by train today.","th":"เราเดินทางโดยรถไฟวันนี้","lv":"A1","cat":"travel","note":"present simple. 'by train' = โดยรถไฟ, ใช้ by + พาหนะ ไม่ใส่ article."},
  {"en":"She has a small bag.","th":"เธอมีกระเป๋าใบเล็ก","lv":"A1","cat":"travel","note":"present simple กับ has (ประธานเอกพจน์). 'a small bag' = article a + adjective + noun."},
  {"en":"The hotel is very big.","th":"โรงแรมใหญ่มาก","lv":"A1","cat":"travel","note":"verb to be (is) บอกลักษณะ. 'very' ขยาย adjective big."},
  {"en":"I have two tickets.","th":"ฉันมีตั๋วสองใบ","lv":"A1","cat":"travel","note":"present simple กับ have. 'two tickets' = เลข + นามพหูพจน์ เติม s."},
  {"en":"They wait at the gate.","th":"พวกเขารออยู่ที่ประตูทางออก","lv":"A1","cat":"travel","note":"present simple. 'at the gate' = preposition at บอกตำแหน่ง."},
  {"en":"He looks at the map.","th":"เขามองดูแผนที่","lv":"A1","cat":"travel","note":"present simple กับ looks. 'look at' = มองดู (phrasal verb + at)."},
  {"en":"My room is on the left.","th":"ห้องของฉันอยู่ทางซ้าย","lv":"A1","cat":"travel","note":"verb to be (is). 'on the left' = ทางซ้าย, ใช้ on บอกทิศ."},
  {"en":"We need a taxi now.","th":"เราต้องการแท็กซี่ตอนนี้","lv":"A1","cat":"travel","note":"present simple กับ need. 'a taxi' = article a + noun."},
  {"en":"Is the bus here yet?","th":"รถบัสมาถึงหรือยัง?","lv":"A1","cat":"travel","note":"คำถาม verb to be ขึ้นต้นด้วย Is. 'yet' = หรือยัง ใช้ในคำถาม."},
  {"en":"I would like to book a room.","th":"ฉันอยากจองห้องพัก","lv":"A2","cat":"travel","note":"'would like to' = อยากจะ (สุภาพกว่า want). ตามด้วย verb base + กรรม."},
  {"en":"The plane leaves at six o'clock.","th":"เครื่องบินออกตอนหกโมง","lv":"A2","cat":"travel","note":"present simple บอกตารางเวลา. 'at six o'clock' = at + เวลา."},
  {"en":"Can you show me the way?","th":"ช่วยบอกทางให้ฉันหน่อยได้ไหม?","lv":"A2","cat":"travel","note":"คำถามขอร้องด้วย Can. 'show me the way' = บอกทาง (verb + กรรมรอง me + กรรมตรง)."},
  {"en":"We are staying for three nights.","th":"เราพักสามคืน","lv":"A2","cat":"travel","note":"present continuous บอกแผน. 'for three nights' = for + ช่วงเวลา."},
  {"en":"How much is a single ticket?","th":"ตั๋วเที่ยวเดียวราคาเท่าไร?","lv":"A2","cat":"travel","note":"คำถามราคาด้วย 'How much'. 'a single ticket' = ตั๋วเที่ยวเดียว."},
  {"en":"I forgot my passport at home.","th":"ฉันลืมพาสปอร์ตไว้ที่บ้าน","lv":"A2","cat":"travel","note":"past simple กับ forgot (กริยาช่อง 2 ของ forget). 'at home' ไม่ใส่ article."},
  {"en":"The train was ten minutes late.","th":"รถไฟมาช้าสิบนาที","lv":"A2","cat":"travel","note":"past simple กับ was. 'ten minutes late' = ช้าสิบนาที (เวลา + late)."},
  {"en":"Please put your bag here.","th":"กรุณาวางกระเป๋าตรงนี้","lv":"A2","cat":"travel","note":"ประโยคคำสั่งสุภาพด้วย Please + verb. 'here' บอกตำแหน่ง."},
  {"en":"We must check in before noon.","th":"เราต้องเช็คอินก่อนเที่ยง","lv":"A2","cat":"travel","note":"'must' = ต้อง (จำเป็น). 'check in' = เช็คอิน, 'before noon' = ก่อนเที่ยง."},
  {"en":"Turn right after the bank.","th":"เลี้ยวขวาหลังจากธนาคาร","lv":"A2","cat":"travel","note":"ประโยคคำสั่งบอกทางด้วย verb 'turn'. 'after the bank' = after + สถานที่."},
  {"en":"I have already booked our flight tickets.","th":"ฉันจองตั๋วเครื่องบินของเราไว้แล้ว","lv":"B1","cat":"travel","note":"present perfect (have + booked) กับ 'already' บอกว่าทำเสร็จแล้ว."},
  {"en":"If it rains, we will stay inside.","th":"ถ้าฝนตก เราจะอยู่ข้างใน","lv":"B1","cat":"travel","note":"first conditional: if + present simple, will + verb. บอกเงื่อนไขที่เป็นไปได้."},
  {"en":"The flight has been delayed for hours.","th":"เที่ยวบินถูกเลื่อนออกไปหลายชั่วโมง","lv":"B1","cat":"travel","note":"present perfect passive (has been + delayed). 'for hours' = นานหลายชั่วโมง."},
  {"en":"We are looking for a cheaper hotel.","th":"เรากำลังหาโรงแรมที่ถูกกว่า","lv":"B1","cat":"travel","note":"present continuous กับ 'look for' = ค้นหา. 'cheaper' = comparative ของ cheap."},
  {"en":"You should arrive at the airport early.","th":"คุณควรไปถึงสนามบินแต่เนิ่นๆ","lv":"B1","cat":"travel","note":"'should' = ควร แนะนำ. 'arrive at' = ไปถึง (ใช้ at กับสถานที่เฉพาะ)."},
  {"en":"I have never travelled abroad before.","th":"ฉันไม่เคยเดินทางไปต่างประเทศมาก่อน","lv":"B1","cat":"travel","note":"present perfect กับ 'never' บอกประสบการณ์. 'abroad' = ต่างประเทศ (adverb ไม่ใส่ to)."},
  {"en":"Could you tell me where the station is?","th":"คุณช่วยบอกฉันได้ไหมว่าสถานีอยู่ที่ไหน?","lv":"B1","cat":"travel","note":"คำถามทางอ้อม: 'where the station is' เรียงแบบบอกเล่า. 'Could you' สุภาพ."},
  {"en":"They missed the last bus home.","th":"พวกเขาพลาดรถบัสเที่ยวสุดท้ายกลับบ้าน","lv":"B1","cat":"travel","note":"past simple กับ missed. 'the last bus' = รถเที่ยวสุดท้าย, 'home' เป็น adverb."},
  {"en":"We need to change trains at the next stop.","th":"เราต้องเปลี่ยนรถไฟที่ป้ายถัดไป","lv":"B1","cat":"travel","note":"'need to' + verb = จำเป็นต้อง. 'change trains' ใช้พหูพจน์, 'at the next stop' บอกที่."},
  {"en":"The guide showed us around the old town.","th":"ไกด์พาเราเที่ยวรอบเมืองเก่า","lv":"B1","cat":"travel","note":"past simple กับ 'show around' = พาชมรอบๆ. 'the old town' = เมืองเก่า."},
  {"en":"If we had left earlier, we would have caught the train.","th":"ถ้าเราออกเร็วกว่านี้ เราคงจะทันรถไฟ","lv":"B2","cat":"travel","note":"third conditional: if + past perfect, would have + V3 บอกเหตุการณ์ในอดีตที่ไม่เกิดจริง."},
  {"en":"Our luggage was lost somewhere during the connecting flight.","th":"สัมภาระของเราหายไปที่ไหนสักแห่งระหว่างเที่ยวบินต่อ","lv":"B2","cat":"travel","note":"past simple passive (was lost). 'connecting flight' = เที่ยวบินต่อเครื่อง, 'during' = ระหว่าง."},
  {"en":"I wish I had booked the room in advance.","th":"ฉันหวังว่าฉันได้จองห้องไว้ล่วงหน้า","lv":"B2","cat":"travel","note":"'I wish + past perfect' บอกความเสียดายในอดีต. 'in advance' = ล่วงหน้า."},
  {"en":"The tour was cancelled because of the heavy storm.","th":"ทัวร์ถูกยกเลิกเพราะพายุรุนแรง","lv":"B2","cat":"travel","note":"past passive (was cancelled). 'because of' + นาม = เพราะ. 'heavy storm' = พายุรุนแรง."},
  {"en":"You had better confirm your booking before you leave.","th":"คุณควรยืนยันการจองก่อนออกเดินทาง","lv":"B2","cat":"travel","note":"'had better' = ควรอย่างยิ่ง (เตือน). 'before you leave' = อนุประโยคเวลา."},
  {"en":"By the time we arrived, the last train had gone.","th":"พอเราไปถึง รถไฟเที่ยวสุดท้ายก็ออกไปแล้ว","lv":"B2","cat":"travel","note":"past perfect (had gone) บอกเหตุการณ์ที่เกิดก่อน. 'by the time' = พอถึงตอนที่."},
  {"en":"Travelling alone has taught me to be more independent.","th":"การเดินทางคนเดียวสอนให้ฉันพึ่งพาตัวเองมากขึ้น","lv":"B2","cat":"travel","note":"gerund 'travelling' เป็นประธาน. present perfect (has taught). 'more independent' = comparative."},
  {"en":"We were planning to visit the coast, but the weather changed.","th":"เราวางแผนจะไปเที่ยวชายฝั่ง แต่อากาศเปลี่ยน","lv":"B2","cat":"travel","note":"past continuous (were planning) บอกแผนในอดีต. 'but' เชื่อมประโยคขัดแย้ง."},
  {"en":"The flight would have been cheaper if we had booked sooner.","th":"เที่ยวบินคงจะถูกกว่านี้ถ้าเราจองเร็วกว่านี้","lv":"B2","cat":"travel","note":"third conditional แบบสลับ: would have been + if + past perfect. 'sooner' = เร็วกว่า."},
  {"en":"Visitors are advised to keep their passports safe at all times.","th":"นักท่องเที่ยวควรเก็บพาสปอร์ตให้ปลอดภัยตลอดเวลา","lv":"B2","cat":"travel","note":"passive 'are advised to' = ได้รับคำแนะนำให้. 'at all times' = ตลอดเวลา."},
  // ── ร้านอาหารและคาเฟ่ (food) ──
  {"en":"I want some water.","th":"ฉันขอน้ำหน่อย","lv":"A1","cat":"food","note":"'some' ใช้กับ uncountable เช่น water. ประโยคบอกเล่า present simple กับ want."},
  {"en":"The coffee is hot.","th":"กาแฟร้อน","lv":"A1","cat":"food","note":"'The' ชี้เฉพาะกาแฟที่พูดถึง. โครงสร้าง subject + be + adjective."},
  {"en":"Can I have the menu?","th":"ขอเมนูหน่อยได้ไหม","lv":"A1","cat":"food","note":"'Can I have...?' ขอสิ่งของแบบสุภาพ. 'the menu' ชี้เฉพาะเมนูของร้านนี้."},
  {"en":"I like this cake.","th":"ฉันชอบเค้กชิ้นนี้","lv":"A1","cat":"food","note":"present simple กับ like. 'this' ชี้สิ่งที่อยู่ใกล้."},
  {"en":"We need two forks.","th":"เราต้องการส้อมสองอัน","lv":"A1","cat":"food","note":"'two forks' นับได้เติม -s. present simple กับ need."},
  {"en":"The food is good.","th":"อาหารอร่อย","lv":"A1","cat":"food","note":"subject + be + adjective. 'food' เป็น uncountable ไม่เติม -s."},
  {"en":"I want a cold drink.","th":"ฉันอยากได้เครื่องดื่มเย็นๆ","lv":"A1","cat":"food","note":"'a' ใช้กับ drink ที่นับได้และขึ้นต้นเสียงพยัญชนะ. cold เป็น adjective ขยาย drink."},
  {"en":"Please bring some bread.","th":"ช่วยเอาขนมปังมาหน่อย","lv":"A1","cat":"food","note":"ประโยคคำสั่งสุภาพขึ้นต้นด้วย Please + verb. 'bread' เป็น uncountable ใช้ some."},
  {"en":"Is the tea ready?","th":"ชาพร้อมหรือยัง","lv":"A1","cat":"food","note":"คำถาม yes/no ขึ้นต้นด้วย Is. 'ready' เป็น adjective."},
  {"en":"I love this soup.","th":"ฉันชอบซุปนี้มาก","lv":"A1","cat":"food","note":"present simple กับ love. 'soup' เป็น uncountable แต่ใช้ this ชี้ชามที่กิน."},
  {"en":"I would like a coffee, please.","th":"ขอกาแฟหนึ่งแก้วครับ","lv":"A2","cat":"food","note":"'would like' สุภาพกว่า want. 'a coffee' หมายถึงกาแฟหนึ่งแก้วในบริบทร้าน."},
  {"en":"Could we book a table tonight?","th":"เราจองโต๊ะคืนนี้ได้ไหม","lv":"A2","cat":"food","note":"'Could we...?' ขออนุญาตแบบสุภาพ. 'book a table' = จองโต๊ะ."},
  {"en":"How much is the cheese cake?","th":"ชีสเค้กราคาเท่าไหร่","lv":"A2","cat":"food","note":"'How much is...?' ถามราคาสิ่งของชิ้นเดียว. ใช้ is เพราะ subject เอกพจน์."},
  {"en":"The waiter is very friendly.","th":"พนักงานเสิร์ฟเป็นมิตรมาก","lv":"A2","cat":"food","note":"subject + be + adverb + adjective. 'very' ขยาย friendly."},
  {"en":"Can you bring the bill, please?","th":"ขอบิลหน่อยได้ไหมคะ","lv":"A2","cat":"food","note":"'Can you...?' ขอให้ทำสิ่งใดสิ่งหนึ่ง. 'the bill' = ใบเก็บเงิน."},
  {"en":"I am looking for a quiet cafe.","th":"ฉันกำลังหาคาเฟ่เงียบๆ","lv":"A2","cat":"food","note":"present continuous (am + looking) บอกสิ่งที่กำลังทำตอนนี้. 'look for' = มองหา."},
  {"en":"She does not eat meat.","th":"เธอไม่กินเนื้อสัตว์","lv":"A2","cat":"food","note":"present simple ปฏิเสธ ใช้ does not + verb base. 'meat' เป็น uncountable."},
  {"en":"We are ready to order now.","th":"เราพร้อมสั่งอาหารแล้ว","lv":"A2","cat":"food","note":"be + ready to + verb = พร้อมจะทำ. 'order' = สั่งอาหาร."},
  {"en":"This dessert tastes really sweet.","th":"ของหวานนี้รสหวานมากจริงๆ","lv":"A2","cat":"food","note":"verb 'taste' + adjective บอกรสชาติ. 'really' ขยาย sweet."},
  {"en":"Do you have any green tea?","th":"มีชาเขียวไหม","lv":"A2","cat":"food","note":"คำถาม present simple ใช้ Do you have. 'any' ใช้ในคำถามกับ uncountable เช่น tea."},
  {"en":"I have already paid for the meal.","th":"ฉันจ่ายค่าอาหารไปแล้ว","lv":"B1","cat":"food","note":"present perfect (have + paid) + already บอกว่าทำเสร็จแล้ว. 'pay for' = จ่ายค่า."},
  {"en":"Could you tell me what you recommend?","th":"ช่วยบอกหน่อยว่าคุณแนะนำอะไร","lv":"B1","cat":"food","note":"'Could you...?' สุภาพ + indirect question 'what you recommend' (ไม่กลับรูปคำถาม)."},
  {"en":"We have been waiting for our food.","th":"เรารออาหารมาสักพักแล้ว","lv":"B1","cat":"food","note":"present perfect continuous (have been + waiting) บอกการกระทำที่ดำเนินมาต่อเนื่อง."},
  {"en":"If you want, I can order for you.","th":"ถ้าคุณต้องการ ฉันสั่งให้ได้นะ","lv":"B1","cat":"food","note":"first conditional 'If + present, ... can'. 'order for you' = สั่งแทนคุณ."},
  {"en":"The waiter brought us the wrong dish.","th":"พนักงานเสิร์ฟเอาจานผิดมาให้เรา","lv":"B1","cat":"food","note":"past simple 'brought' (กริยาช่อง 2 ของ bring). 'wrong dish' = อาหารผิดจาน."},
  {"en":"I think this restaurant is too expensive.","th":"ฉันว่าร้านนี้แพงเกินไป","lv":"B1","cat":"food","note":"'I think' + clause แสดงความเห็น. 'too + adjective' = เกินไป."},
  {"en":"They are serving breakfast until eleven o'clock.","th":"พวกเขาเสิร์ฟอาหารเช้าถึงสิบเอ็ดโมง","lv":"B1","cat":"food","note":"present continuous บอกช่วงที่ทำอยู่. 'until' บอกเวลาสิ้นสุด."},
  {"en":"Would you like something to drink first?","th":"รับเครื่องดื่มก่อนไหมคะ","lv":"B1","cat":"food","note":"'Would you like...?' เสนอแบบสุภาพ. 'something to drink' = อะไรสักอย่างไว้ดื่ม."},
  {"en":"The coffee here is much better than tea.","th":"กาแฟที่นี่ดีกว่าชามาก","lv":"B1","cat":"food","note":"comparative 'better than' + 'much' เน้นว่าดีกว่าเยอะ. better เป็นรูปเปรียบเทียบของ good."},
  {"en":"Can we share one plate of pasta?","th":"เราขอแบ่งพาสต้าจานเดียวได้ไหม","lv":"B1","cat":"food","note":"'Can we...?' ขออนุญาต. 'a plate of pasta' ใช้บอกปริมาณกับ pasta ที่ uncountable."},
  {"en":"I would have ordered the fish if it were fresh.","th":"ฉันคงสั่งปลาถ้ามันสดกว่านี้","lv":"B2","cat":"food","note":"mixed conditional 'would have + V3 ... if + were' พูดถึงสิ่งที่ไม่เกิดขึ้นจริง."},
  {"en":"The dessert was so rich that I couldn't finish it.","th":"ของหวานเข้มข้นมากจนฉันกินไม่หมด","lv":"B2","cat":"food","note":"'so + adjective + that...' แสดงผลลัพธ์. 'couldn't' = ไม่สามารถในอดีต."},
  {"en":"Had I known it was busy, I would have booked earlier.","th":"ถ้ารู้ว่าคนเยอะ ฉันคงจองไว้ก่อนแล้ว","lv":"B2","cat":"food","note":"inversion conditional 'Had I known...' แทน 'If I had known'. เน้นเสียดายในอดีต."},
  {"en":"The waiter suggested that we try the daily special.","th":"พนักงานเสิร์ฟแนะนำให้เราลองเมนูพิเศษประจำวัน","lv":"B2","cat":"food","note":"'suggest that + subject + base verb' (subjunctive). 'daily special' = เมนูพิเศษประจำวัน."},
  {"en":"This is the best espresso I have ever tasted.","th":"นี่เป็นเอสเพรสโซที่ดีที่สุดที่ฉันเคยลิ้มลอง","lv":"B2","cat":"food","note":"superlative 'the best' + relative clause กับ present perfect 'have ever tasted'."},
  {"en":"We were told the kitchen would close at ten.","th":"เราได้รับแจ้งว่าครัวจะปิดตอนสี่ทุ่ม","lv":"B2","cat":"food","note":"passive อดีต 'were told' + reported speech 'would close' (เลื่อน will เป็น would)."},
  {"en":"If the service had been faster, we might have stayed longer.","th":"ถ้าบริการเร็วกว่านี้ เราอาจอยู่ต่อนานกว่านี้","lv":"B2","cat":"food","note":"third conditional 'If + had been ... might have + V3' พูดถึงผลที่เป็นไปได้ในอดีต."},
  {"en":"Although the cafe looked small, it served amazing food.","th":"ถึงคาเฟ่จะดูเล็ก แต่ก็เสิร์ฟอาหารอร่อยมาก","lv":"B2","cat":"food","note":"'Although + clause' แสดงความขัดแย้ง. past simple looked/served."},
  {"en":"I wish I had reserved a table by the window.","th":"ฉันอยากให้ตัวเองจองโต๊ะริมหน้าต่างไว้จัง","lv":"B2","cat":"food","note":"'wish + past perfect (had reserved)' แสดงความเสียดายเรื่องในอดีต."},
  {"en":"The bill came to more than we had expected.","th":"ค่าอาหารแพงกว่าที่เราคาดไว้","lv":"B2","cat":"food","note":"'come to' = รวมเป็นยอด. past perfect 'had expected' บอกเหตุการณ์ก่อนหน้าในอดีต."},
  // ── การทำงานและธุรกิจ (work) ──
  {"en":"I have a job.","th":"ฉันมีงานทำ","lv":"A1","cat":"work","note":"present simple, 'have' บอกการครอบครอง. 'a job' นับได้ใช้ a."},
  {"en":"We work in an office.","th":"เราทำงานในออฟฟิศ","lv":"A1","cat":"work","note":"present simple. 'in an office' ใช้ in กับสถานที่ปิด."},
  {"en":"The boss is here.","th":"เจ้านายอยู่ที่นี่","lv":"A1","cat":"work","note":"verb to be 'is'. 'here' บอกสถานที่."},
  {"en":"I send an email.","th":"ฉันส่งอีเมล","lv":"A1","cat":"work","note":"present simple. 'send' กริยา, 'an email' นับได้ใช้ an นำสระ."},
  {"en":"We have a meeting today.","th":"เรามีประชุมวันนี้","lv":"A1","cat":"work","note":"present simple. 'today' บอกเวลา ไม่ใช้ preposition."},
  {"en":"The client is happy.","th":"ลูกค้ามีความสุข","lv":"A1","cat":"work","note":"verb to be 'is' + คำคุณศัพท์ happy."},
  {"en":"I start work at eight.","th":"ฉันเริ่มงานตอนแปดโมง","lv":"A1","cat":"work","note":"present simple. 'at eight' ใช้ at กับเวลานาฬิกา."},
  {"en":"My desk is clean.","th":"โต๊ะทำงานของฉันสะอาด","lv":"A1","cat":"work","note":"verb to be 'is'. 'my' บอกความเป็นเจ้าของ."},
  {"en":"We need a plan.","th":"เราต้องการแผน","lv":"A1","cat":"work","note":"present simple. 'need' บอกความจำเป็น, 'a plan' นับได้."},
  {"en":"The report is ready.","th":"รายงานพร้อมแล้ว","lv":"A1","cat":"work","note":"verb to be 'is' + ready คำคุณศัพท์."},
  {"en":"She is writing a report.","th":"เธอกำลังเขียนรายงาน","lv":"A2","cat":"work","note":"present continuous (is + V-ing) บอกสิ่งที่ทำอยู่ตอนนี้."},
  {"en":"I will call the client later.","th":"ฉันจะโทรหาลูกค้าทีหลัง","lv":"A2","cat":"work","note":"future 'will + V'. 'later' บอกเวลาในอนาคต."},
  {"en":"We finished the project on time.","th":"เราทำโปรเจกต์เสร็จตรงเวลา","lv":"A2","cat":"work","note":"past simple 'finished'. 'on time' สำนวนแปลว่าตรงเวลา."},
  {"en":"He works for a big company.","th":"เขาทำงานให้บริษัทใหญ่","lv":"A2","cat":"work","note":"present simple. 'work for' = ทำงานให้/สังกัด."},
  {"en":"The meeting starts at ten.","th":"การประชุมเริ่มตอนสิบโมง","lv":"A2","cat":"work","note":"present simple บอกตารางเวลา. 'at ten' ใช้ at กับเวลา."},
  {"en":"I have an interview on Monday.","th":"ฉันมีสัมภาษณ์งานวันจันทร์","lv":"A2","cat":"work","note":"'on Monday' ใช้ on กับวัน. 'an interview' นับได้."},
  {"en":"They are talking to the manager.","th":"พวกเขากำลังคุยกับผู้จัดการ","lv":"A2","cat":"work","note":"present continuous. 'talk to' = คุยกับ."},
  {"en":"Please send me the file.","th":"กรุณาส่งไฟล์ให้ฉันด้วย","lv":"A2","cat":"work","note":"ประโยคคำสั่งสุภาพด้วย 'please'. 'send me' กริยาสองกรรม."},
  {"en":"My salary comes at the end of the month.","th":"เงินเดือนฉันออกตอนสิ้นเดือน","lv":"A2","cat":"work","note":"present simple. 'at the end of' สำนวนบอกช่วงเวลา."},
  {"en":"We need to book a meeting room.","th":"เราต้องจองห้องประชุม","lv":"A2","cat":"work","note":"'need to + V'. 'book' = จอง."},
  {"en":"Could you check the report before the meeting?","th":"คุณช่วยตรวจรายงานก่อนประชุมได้ไหม","lv":"B1","cat":"work","note":"คำขอสุภาพ 'could you'. 'before' บอกลำดับเวลา."},
  {"en":"I have been waiting for your reply since yesterday.","th":"ฉันรอคำตอบของคุณตั้งแต่เมื่อวาน","lv":"B1","cat":"work","note":"present perfect continuous. 'since yesterday' จุดเริ่มเวลา."},
  {"en":"We should finish this task by Friday.","th":"เราควรทำงานนี้ให้เสร็จภายในวันศุกร์","lv":"B1","cat":"work","note":"'should' คำแนะนำ. 'by Friday' = ภายในวันศุกร์ (เส้นตาย)."},
  {"en":"The manager asked me to prepare a report.","th":"ผู้จัดการขอให้ฉันเตรียมรายงาน","lv":"B1","cat":"work","note":"past simple. 'ask someone to do' โครงสร้างขอให้ทำ."},
  {"en":"If you have any questions, please email me.","th":"ถ้ามีคำถามอะไร กรุณาอีเมลหาฉัน","lv":"B1","cat":"work","note":"เงื่อนไขแบบที่ 1 (if + present, ...). 'email' เป็นกริยาได้."},
  {"en":"I am looking forward to the new project.","th":"ฉันตั้งตารอโปรเจกต์ใหม่","lv":"B1","cat":"work","note":"'look forward to + นาม/V-ing' = ตั้งตารอ."},
  {"en":"She has worked here for five years.","th":"เธอทำงานที่นี่มาห้าปีแล้ว","lv":"B1","cat":"work","note":"present perfect. 'for five years' ระยะเวลา."},
  {"en":"We are going to hire two new people.","th":"เรากำลังจะจ้างคนใหม่สองคน","lv":"B1","cat":"work","note":"'be going to' บอกแผนอนาคต. 'hire' = จ้าง."},
  {"en":"The deadline was moved to next week.","th":"เส้นตายถูกเลื่อนไปสัปดาห์หน้า","lv":"B1","cat":"work","note":"past simple passive (was + V3). 'move to' = เลื่อนไป."},
  {"en":"Can we reschedule the meeting to tomorrow afternoon?","th":"เราเลื่อนนัดประชุมเป็นบ่ายพรุ่งนี้ได้ไหม","lv":"B1","cat":"work","note":"คำขอ 'can we'. 'reschedule' = เลื่อนนัด."},
  {"en":"I would appreciate it if you could reply by the end of the day.","th":"ฉันจะขอบคุณมากถ้าคุณตอบกลับได้ภายในสิ้นวัน","lv":"B2","cat":"work","note":"คำขอสุภาพมาก 'I would appreciate it if'. 'by the end of the day' เส้นตาย."},
  {"en":"The client has been complaining about the delivery delays.","th":"ลูกค้าบ่นเรื่องการส่งของล่าช้ามาตลอด","lv":"B2","cat":"work","note":"present perfect continuous. 'complain about' บ่นเรื่อง."},
  {"en":"We need to make sure the budget covers all the costs.","th":"เราต้องแน่ใจว่างบประมาณครอบคลุมค่าใช้จ่ายทั้งหมด","lv":"B2","cat":"work","note":"'make sure that' = ทำให้แน่ใจว่า. 'cover' = ครอบคลุม."},
  {"en":"Although the project was difficult, we delivered it on time.","th":"แม้โปรเจกต์จะยาก แต่เราก็ส่งมอบตรงเวลา","lv":"B2","cat":"work","note":"'although' = แม้ว่า ตามด้วยอนุประโยค. past simple."},
  {"en":"The interview went well, so they offered me the job.","th":"การสัมภาษณ์เป็นไปด้วยดี พวกเขาเลยเสนองานให้ฉัน","lv":"B2","cat":"work","note":"past simple. 'so' บอกผลลัพธ์. 'offer someone something' เสนอให้."},
  {"en":"Before you leave, please make sure you have signed the contract.","th":"ก่อนคุณกลับ ช่วยแน่ใจว่าคุณเซ็นสัญญาแล้ว","lv":"B2","cat":"work","note":"'before' + present, ... คำสั่ง. 'have signed' present perfect ใน clause."},
  {"en":"I think we should discuss the new salary policy next week.","th":"ฉันคิดว่าเราควรคุยเรื่องนโยบายเงินเดือนใหม่สัปดาห์หน้า","lv":"B2","cat":"work","note":"'I think (that)'. 'discuss' ตามด้วยกรรมโดยตรง ไม่ต้องมี about."},
  {"en":"The manager wants everyone to attend the meeting on Friday morning.","th":"ผู้จัดการอยากให้ทุกคนเข้าประชุมเช้าวันศุกร์","lv":"B2","cat":"work","note":"'want someone to do'. 'attend' = เข้าร่วม. 'on Friday morning' ใช้ on กับวัน."},
  {"en":"If we had more time, we could improve the presentation.","th":"ถ้าเรามีเวลามากกว่านี้ เราคงปรับงานนำเสนอให้ดีขึ้นได้","lv":"B2","cat":"work","note":"เงื่อนไขแบบที่ 2 (if + past, would/could + V) เรื่องสมมติ."},
  {"en":"Our team has been working hard to meet the deadline this month.","th":"ทีมเราทำงานหนักเพื่อให้ทันเส้นตายเดือนนี้","lv":"B2","cat":"work","note":"present perfect continuous. 'meet the deadline' = ทำให้ทันเส้นตาย."},
  // ── การช้อปปิ้ง (shopping) ──
  {"en":"How much is this bag?","th":"กระเป๋าใบนี้ราคาเท่าไหร่","lv":"A1","cat":"shopping","note":"'How much' ถามราคา/นับไม่ได้. 'this bag' ใช้ this ชี้ของใกล้ตัวเอกพจน์."},
  {"en":"I want a new shirt.","th":"ฉันอยากได้เสื้อตัวใหม่","lv":"A1","cat":"shopping","note":"'a new shirt' article a + คำขึ้นต้นเสียงพยัญชนะ. โครงสร้าง I want + กรรม."},
  {"en":"The shop is open now.","th":"ร้านเปิดแล้วตอนนี้","lv":"A1","cat":"shopping","note":"'The shop' the ชี้สิ่งที่รู้จัก. 'now' บอกเวลาปัจจุบัน."},
  {"en":"These shoes are big.","th":"รองเท้าคู่นี้ใหญ่","lv":"A1","cat":"shopping","note":"'These shoes' these ชี้ของใกล้ตัวพหูพจน์. are ใช้กับพหูพจน์."},
  {"en":"I like that red dress.","th":"ฉันชอบชุดสีแดงตัวนั้น","lv":"A1","cat":"shopping","note":"'that dress' that ชี้ของไกลตัวเอกพจน์. red สี วางหน้านาม."},
  {"en":"Where is the market?","th":"ตลาดอยู่ที่ไหน","lv":"A1","cat":"shopping","note":"'Where is' ถามสถานที่เอกพจน์. 'the market' the ชี้สิ่งเฉพาะ."},
  {"en":"This is too small.","th":"อันนี้เล็กเกินไป","lv":"A1","cat":"shopping","note":"'too small' too + คุณศัพท์ = มากเกินไป. this เป็นประธาน."},
  {"en":"Do you have a basket?","th":"คุณมีตะกร้าไหม","lv":"A1","cat":"shopping","note":"คำถาม Do you have. 'a basket' article a ของเอกพจน์นับได้."},
  {"en":"I need new black shoes.","th":"ฉันต้องการรองเท้าสีดำคู่ใหม่","lv":"A1","cat":"shopping","note":"I need + กรรมพหูพจน์ ไม่ใช้ a. ลำดับคำ new black shoes."},
  {"en":"What color is it?","th":"มันสีอะไร","lv":"A1","cat":"shopping","note":"'What color' ถามสี. 'is it' กริยา is + ประธาน it เอกพจน์."},
  {"en":"Can I try this jacket on?","th":"ฉันลองเสื้อแจ็กเก็ตตัวนี้ได้ไหม","lv":"A2","cat":"shopping","note":"'try on' กริยาวลีแยกได้ ใส่กรรมตรงกลาง. Can I ขออนุญาต."},
  {"en":"How much do these socks cost?","th":"ถุงเท้าพวกนี้ราคาเท่าไหร่","lv":"A2","cat":"shopping","note":"'How much do ... cost' ถามราคาด้วย do. these พหูพจน์."},
  {"en":"Is there a sale today?","th":"วันนี้มีลดราคาไหม","lv":"A2","cat":"shopping","note":"'Is there' ถามมีหรือไม่เอกพจน์. 'a sale' article a."},
  {"en":"I would like a smaller size.","th":"ฉันขอไซซ์เล็กกว่านี้หน่อย","lv":"A2","cat":"shopping","note":"'I would like' สุภาพกว่า want. 'smaller' comparative -er."},
  {"en":"Can I pay by credit card?","th":"ฉันจ่ายด้วยบัตรเครดิตได้ไหม","lv":"A2","cat":"shopping","note":"'pay by credit card' จ่ายด้วยวิธี. Can I ขออนุญาต."},
  {"en":"The big shops are too expensive.","th":"ร้านใหญ่ๆ แพงเกินไป","lv":"A2","cat":"shopping","note":"'too expensive' too + คุณศัพท์. 'shops' พหูพจน์เติม -s."},
  {"en":"How many apples do you want?","th":"คุณต้องการแอปเปิลกี่ลูก","lv":"A2","cat":"shopping","note":"'How many' ถามจำนวนของนับได้. apples พหูพจน์."},
  {"en":"This dress is cheaper than that one.","th":"ชุดตัวนี้ถูกกว่าตัวนั้น","lv":"A2","cat":"shopping","note":"comparative 'cheaper than'. 'that one' one แทนนามไม่ซ้ำคำ."},
  {"en":"Do you sell bags here?","th":"ที่นี่ขายกระเป๋าไหม","lv":"A2","cat":"shopping","note":"'Do you sell' คำถาม present simple. bags พหูพจน์ทั่วไปไม่ใส่ article."},
  {"en":"I am looking for a gift.","th":"ฉันกำลังหาของขวัญอยู่","lv":"A2","cat":"shopping","note":"present continuous 'am looking for'. 'a gift' article a."},
  {"en":"Could you show me a cheaper one?","th":"ช่วยหาแบบที่ถูกกว่านี้ให้ดูหน่อยได้ไหม","lv":"B1","cat":"shopping","note":"'Could you' สุภาพมาก. comparative cheaper + one แทนนาม."},
  {"en":"This shirt doesn't fit me well.","th":"เสื้อตัวนี้ใส่ไม่ค่อยพอดี","lv":"B1","cat":"shopping","note":"negative doesn't fit. 'well' adverb ขยายกริยา."},
  {"en":"I'd like to return these jeans.","th":"ฉันอยากคืนกางเกงยีนส์พวกนี้","lv":"B1","cat":"shopping","note":"'return' คืนสินค้า. 'these jeans' jeans เป็นพหูพจน์เสมอ."},
  {"en":"Everything is half price during the sale.","th":"ทุกอย่างลดครึ่งราคาช่วงเซล","lv":"B1","cat":"shopping","note":"'Everything' เอกพจน์ + is. 'half price' ครึ่งราคา. during ในช่วง."},
  {"en":"The market sells fresh fruit every morning.","th":"ตลาดขายผลไม้สดทุกเช้า","lv":"B1","cat":"shopping","note":"present simple นิสัย. 'fresh fruit' fruit นับไม่ได้. every morning."},
  {"en":"I bought this coat last week.","th":"ฉันซื้อเสื้อโค้ตตัวนี้เมื่อสัปดาห์ที่แล้ว","lv":"B1","cat":"shopping","note":"past simple 'bought'. 'last week' บอกอดีต."},
  {"en":"Can you give me a small discount?","th":"ลดราคาให้หน่อยได้ไหม","lv":"B1","cat":"shopping","note":"'give me a discount' ลดราคา. Can you ขอความช่วยเหลือ."},
  {"en":"These two colors look the same to me.","th":"สองสีนี้ดูเหมือนกันสำหรับฉัน","lv":"B1","cat":"shopping","note":"'look the same' ดูเหมือนกัน. these two + นามพหูพจน์."},
  {"en":"The mall is busier on the weekend.","th":"ห้างคนเยอะกว่าตอนสุดสัปดาห์","lv":"B1","cat":"shopping","note":"comparative 'busier' (y->i+er). 'on the weekend' บอกเวลา."},
  {"en":"Do you have this jacket in a larger size?","th":"เสื้อแจ็กเก็ตตัวนี้มีไซซ์ใหญ่กว่านี้ไหม","lv":"B1","cat":"shopping","note":"comparative larger. 'in a larger size' in บอกขนาด/รุ่น."},
  {"en":"If you buy two shirts, you get one free.","th":"ถ้าซื้อเสื้อสองตัว จะได้ฟรีหนึ่งตัว","lv":"B2","cat":"shopping","note":"first conditional 'If you buy, you get'. 'one free' แถมหนึ่ง."},
  {"en":"I'd rather pay with cash than a card.","th":"ฉันขอจ่ายเงินสดดีกว่าใช้บัตร","lv":"B2","cat":"shopping","note":"'would rather A than B' ชอบ A มากกว่า. pay with cash/card."},
  {"en":"Could you tell me where the fitting rooms are?","th":"ช่วยบอกหน่อยได้ไหมว่าห้องลองเสื้ออยู่ตรงไหน","lv":"B2","cat":"shopping","note":"indirect question 'where ... are' เรียงแบบบอกเล่า. fitting rooms."},
  {"en":"This is the most expensive watch in the shop.","th":"นี่คือนาฬิกาที่แพงที่สุดในร้าน","lv":"B2","cat":"shopping","note":"superlative 'the most expensive'. 'in the shop' บอกขอบเขต."},
  {"en":"I was hoping to find a cheaper pair of shoes.","th":"ฉันหวังว่าจะเจอรองเท้าที่ถูกกว่านี้สักคู่","lv":"B2","cat":"shopping","note":"past continuous 'was hoping' พูดสุภาพ. 'a pair of shoes' คู่."},
  {"en":"You can return the item if you keep the receipt.","th":"คุณคืนของได้ถ้าเก็บใบเสร็จไว้","lv":"B2","cat":"shopping","note":"conditional 'if you keep'. 'the receipt' ใบเสร็จ. return the item."},
  {"en":"The shirt I ordered online arrived in the wrong color.","th":"เสื้อที่ฉันสั่งออนไลน์มาส่งผิดสี","lv":"B2","cat":"shopping","note":"relative clause 'shirt I ordered' ละ that. 'the wrong color'."},
  {"en":"They were selling everything at a lower price yesterday.","th":"เมื่อวานพวกเขาลดราคาขายทุกอย่างถูกลง","lv":"B2","cat":"shopping","note":"past continuous 'were selling'. comparative 'a lower price'."},
  {"en":"I'm not sure whether this size will fit you properly.","th":"ฉันไม่แน่ใจว่าไซซ์นี้จะใส่พอดีกับคุณไหม","lv":"B2","cat":"shopping","note":"'whether' = ...หรือไม่. future 'will fit'. properly adverb."},
  {"en":"Shopping at the market is much cheaper than at the mall.","th":"ช้อปที่ตลาดถูกกว่าที่ห้างมาก","lv":"B2","cat":"shopping","note":"gerund 'Shopping' เป็นประธาน. 'much cheaper than' เน้น comparative."},
  // ── กาลเวลา (tense) (time) ──
  {"en":"I drink water every day.","th":"ฉันดื่มน้ำทุกวัน","lv":"A1","cat":"time","note":"present simple (drink) คู่กับ 'every day' บอกกิจวัตรที่ทำเป็นประจำ."},
  {"en":"She is reading now.","th":"ตอนนี้เธอกำลังอ่านหนังสือ","lv":"A1","cat":"time","note":"present continuous (is + reading) คู่กับ 'now' บอกสิ่งที่กำลังเกิดขึ้นขณะนี้."},
  {"en":"We go to school every morning.","th":"เราไปโรงเรียนทุกเช้า","lv":"A1","cat":"time","note":"present simple (go) คู่กับ 'every morning' บอกกิจวัตรประจำวัน."},
  {"en":"He is sleeping now.","th":"ตอนนี้เขากำลังนอนหลับ","lv":"A1","cat":"time","note":"present continuous (is + sleeping) คู่กับ 'now' บอกการกระทำที่ดำเนินอยู่ตอนนี้."},
  {"en":"They play football on Sunday.","th":"พวกเขาเล่นฟุตบอลวันอาทิตย์","lv":"A1","cat":"time","note":"present simple (play) คู่กับ 'on Sunday' บอกกิจวัตรที่ทำเป็นประจำ."},
  {"en":"I am eating lunch now.","th":"ตอนนี้ฉันกำลังกินข้าวเที่ยง","lv":"A1","cat":"time","note":"present continuous (am + eating) คู่กับ 'now' บอกสิ่งที่กำลังทำอยู่."},
  {"en":"The sun rises every morning.","th":"ดวงอาทิตย์ขึ้นทุกเช้า","lv":"A1","cat":"time","note":"present simple (rises) คู่กับ 'every morning' บอกความจริงที่เกิดเป็นประจำ."},
  {"en":"My mother cooks every day.","th":"แม่ของฉันทำอาหารทุกวัน","lv":"A1","cat":"time","note":"present simple (cooks) คู่กับ 'every day' บอกกิจวัตรประจำวัน."},
  {"en":"Are you working now?","th":"ตอนนี้คุณกำลังทำงานอยู่ไหม","lv":"A1","cat":"time","note":"present continuous คำถาม (Are + you + working) คู่กับ 'now' ถามสิ่งที่กำลังทำขณะนี้."},
  {"en":"We watch TV every night.","th":"เราดูทีวีทุกคืน","lv":"A1","cat":"time","note":"present simple (watch) คู่กับ 'every night' บอกกิจวัตรที่ทำเป็นประจำ."},
  {"en":"I saw a movie yesterday.","th":"ฉันดูหนังเมื่อวานนี้","lv":"A2","cat":"time","note":"past simple (saw) คู่กับ 'yesterday' บอกเหตุการณ์ที่จบในอดีต."},
  {"en":"She will call you tomorrow.","th":"เธอจะโทรหาคุณพรุ่งนี้","lv":"A2","cat":"time","note":"future (will + call) คู่กับ 'tomorrow' บอกสิ่งที่จะทำในอนาคต."},
  {"en":"We visited grandma last week.","th":"เราไปเยี่ยมคุณยายเมื่อสัปดาห์ที่แล้ว","lv":"A2","cat":"time","note":"past simple (visited) คู่กับ 'last week' บอกเหตุการณ์ที่จบในอดีต."},
  {"en":"I am going to study tonight.","th":"คืนนี้ฉันจะอ่านหนังสือ","lv":"A2","cat":"time","note":"future (be going to + study) คู่กับ 'tonight' บอกแผนการในอนาคต."},
  {"en":"He bought a new phone yesterday.","th":"เขาซื้อโทรศัพท์ใหม่เมื่อวานนี้","lv":"A2","cat":"time","note":"past simple (bought) คู่กับ 'yesterday' บอกเหตุการณ์ที่จบในอดีต."},
  {"en":"They will travel next month.","th":"พวกเขาจะเดินทางเดือนหน้า","lv":"A2","cat":"time","note":"future (will + travel) คู่กับ 'next month' บอกสิ่งที่จะเกิดในอนาคต."},
  {"en":"We arrived home two hours ago.","th":"เราถึงบ้านเมื่อสองชั่วโมงที่แล้ว","lv":"A2","cat":"time","note":"past simple (arrived) คู่กับ 'ago' บอกเวลาที่ผ่านมาในอดีต."},
  {"en":"I am going to meet her later.","th":"ฉันจะไปเจอเธอทีหลัง","lv":"A2","cat":"time","note":"future (be going to + meet) คู่กับ 'later' บอกแผนการในอนาคตอันใกล้."},
  {"en":"Did you sleep well last night?","th":"เมื่อคืนคุณนอนหลับสบายไหม","lv":"A2","cat":"time","note":"past simple คำถาม (Did + you + sleep) คู่กับ 'last night' ถามเหตุการณ์ในอดีต."},
  {"en":"She will finish the work soon.","th":"เธอจะทำงานเสร็จในไม่ช้า","lv":"A2","cat":"time","note":"future (will + finish) คู่กับ 'soon' บอกสิ่งที่จะเกิดในอนาคตอันใกล้."},
  {"en":"I have lived here since 2020.","th":"ฉันอาศัยอยู่ที่นี่มาตั้งแต่ปี 2020","lv":"B1","cat":"time","note":"present perfect (have + lived) คู่กับ 'since' บอกสิ่งที่เริ่มในอดีตและต่อเนื่องถึงปัจจุบัน."},
  {"en":"He has already finished his homework.","th":"เขาทำการบ้านเสร็จแล้ว","lv":"B1","cat":"time","note":"present perfect (has + finished) คู่กับ 'already' เน้นว่าเสร็จก่อนเวลาที่คาด."},
  {"en":"We have known each other for years.","th":"เรารู้จักกันมาหลายปีแล้ว","lv":"B1","cat":"time","note":"present perfect (have + known) คู่กับ 'for' บอกระยะเวลาที่ดำเนินต่อเนื่องถึงตอนนี้."},
  {"en":"Have you ever visited Japan before?","th":"คุณเคยไปญี่ปุ่นมาก่อนไหม","lv":"B1","cat":"time","note":"present perfect คำถาม (Have + you + visited) คู่กับ 'ever' ถามประสบการณ์ในชีวิตที่ผ่านมา."},
  {"en":"She has just left the office.","th":"เธอเพิ่งออกจากออฟฟิศไป","lv":"B1","cat":"time","note":"present perfect (has + left) คู่กับ 'just' เน้นเหตุการณ์ที่เพิ่งเกิดขึ้นไม่นาน."},
  {"en":"They have worked here since March.","th":"พวกเขาทำงานที่นี่มาตั้งแต่เดือนมีนาคม","lv":"B1","cat":"time","note":"present perfect (have + worked) คู่กับ 'since' บอกจุดเริ่มต้นในอดีตที่ต่อเนื่องถึงปัจจุบัน."},
  {"en":"I have not seen him for a week.","th":"ฉันไม่ได้เจอเขามาหนึ่งสัปดาห์แล้ว","lv":"B1","cat":"time","note":"present perfect ปฏิเสธ (have not + seen) คู่กับ 'for' บอกระยะเวลาที่ไม่เกิดเหตุการณ์จนถึงตอนนี้."},
  {"en":"We have eaten there many times.","th":"เรากินที่นั่นมาหลายครั้งแล้ว","lv":"B1","cat":"time","note":"present perfect (have + eaten) คู่กับ 'many times' บอกประสบการณ์ที่เกิดซ้ำจนถึงปัจจุบัน."},
  {"en":"Has the train arrived yet?","th":"รถไฟมาถึงหรือยัง","lv":"B1","cat":"time","note":"present perfect คำถาม (Has + arrived) คู่กับ 'yet' ถามว่าเหตุการณ์ที่คาดไว้เกิดขึ้นแล้วหรือยัง."},
  {"en":"He has studied English for three years.","th":"เขาเรียนภาษาอังกฤษมาสามปีแล้ว","lv":"B1","cat":"time","note":"present perfect (has + studied) คู่กับ 'for' บอกระยะเวลาที่ทำต่อเนื่องถึงตอนนี้."},
  {"en":"I was cooking when she called me yesterday.","th":"ฉันกำลังทำอาหารตอนที่เธอโทรมาเมื่อวานนี้","lv":"B2","cat":"time","note":"past continuous (was + cooking) ตัดกับ past simple (called) คู่กับ 'when/yesterday' บอกเหตุการณ์ที่กำลังเกิดถูกแทรกในอดีต."},
  {"en":"They were watching TV while I was studying.","th":"พวกเขากำลังดูทีวีขณะที่ฉันกำลังอ่านหนังสือ","lv":"B2","cat":"time","note":"past continuous สองเหตุการณ์ (were watching / was studying) คู่กับ 'while' บอกสองสิ่งที่เกิดพร้อมกันในอดีต."},
  {"en":"By tomorrow, I will have finished the report.","th":"ภายในพรุ่งนี้ ฉันจะทำรายงานเสร็จแล้ว","lv":"B2","cat":"time","note":"future perfect (will have + finished) คู่กับ 'by tomorrow' บอกสิ่งที่จะเสร็จก่อนเวลาในอนาคต."},
  {"en":"She has been working here since last year.","th":"เธอทำงานที่นี่มาตั้งแต่ปีที่แล้ว","lv":"B2","cat":"time","note":"present perfect continuous (has been + working) คู่กับ 'since' เน้นการกระทำที่ต่อเนื่องยาวนานถึงปัจจุบัน."},
  {"en":"When I arrived, the meeting had already started.","th":"ตอนที่ฉันมาถึง การประชุมได้เริ่มไปแล้ว","lv":"B2","cat":"time","note":"past perfect (had + started) คู่กับ 'already' บอกเหตุการณ์ที่เกิดก่อนอีกเหตุการณ์ในอดีต."},
  {"en":"He was driving home when it started to rain.","th":"เขากำลังขับรถกลับบ้านตอนที่ฝนเริ่มตก","lv":"B2","cat":"time","note":"past continuous (was + driving) ถูกแทรกด้วย past simple (started) บอกเหตุการณ์ที่กำลังเกิดแล้วมีอีกเหตุการณ์เข้ามา."},
  {"en":"I have been waiting for you for an hour.","th":"ฉันรอคุณมาหนึ่งชั่วโมงแล้ว","lv":"B2","cat":"time","note":"present perfect continuous (have been + waiting) คู่กับ 'for' เน้นระยะเวลาของการกระทำที่ต่อเนื่องถึงตอนนี้."},
  {"en":"By next year, they will have lived here for a decade.","th":"ภายในปีหน้า พวกเขาจะอาศัยอยู่ที่นี่ครบสิบปี","lv":"B2","cat":"time","note":"future perfect (will have + lived) คู่กับ 'by next year' และ 'for' บอกระยะเวลาที่จะครบในอนาคต."},
  {"en":"She had been sleeping before the phone rang.","th":"เธอนอนหลับอยู่ก่อนที่โทรศัพท์จะดัง","lv":"B2","cat":"time","note":"past perfect continuous (had been + sleeping) คู่กับ 'before' บอกการกระทำที่ดำเนินต่อเนื่องก่อนอีกเหตุการณ์ในอดีต."},
  {"en":"We were having dinner when he suddenly arrived.","th":"เรากำลังกินข้าวเย็นตอนที่เขามาถึงอย่างกะทันหัน","lv":"B2","cat":"time","note":"past continuous (were + having) ถูกแทรกด้วย past simple (arrived) คู่กับ 'when' บอกเหตุการณ์ที่กำลังเกิดถูกขัดจังหวะในอดีต."},
  // ── ชนิดของคำ (pos) ──
  {"en":"The dog runs fast.","th":"สุนัขวิ่งเร็ว","lv":"A1","cat":"pos","note":"'dog' เป็น noun (คำนาม) ทำหน้าที่เป็นประธานของประโยค. noun คือคำที่ใช้เรียกคน สัตว์ สิ่งของ."},
  {"en":"I like my cat.","th":"ฉันชอบแมวของฉัน","lv":"A1","cat":"pos","note":"'I' เป็น pronoun (คำสรรพนาม) ใช้แทนตัวผู้พูด. 'my' เป็น determiner บอกความเป็นเจ้าของ."},
  {"en":"She sings well.","th":"เธอร้องเพลงเก่ง","lv":"A1","cat":"pos","note":"'sings' เป็น verb (คำกริยา) บอกการกระทำ. 'well' เป็น adverb ขยายกริยาบอกว่าทำได้ดีแค่ไหน."},
  {"en":"The car is red.","th":"รถคันนี้สีแดง","lv":"A1","cat":"pos","note":"'red' เป็น adjective (คำคุณศัพท์) ขยาย noun 'car' บอกสีของรถ. 'The' เป็น article."},
  {"en":"He sits on it.","th":"เขานั่งบนมัน","lv":"A1","cat":"pos","note":"'on' เป็น preposition (คำบุพบท) บอกตำแหน่ง. 'it' เป็น pronoun แทนสิ่งของ."},
  {"en":"We eat and play.","th":"เรากินและเล่น","lv":"A1","cat":"pos","note":"'and' เป็น conjunction (คำเชื่อม) เชื่อมกริยา 'eat' กับ 'play' เข้าด้วยกัน."},
  {"en":"A bird can fly.","th":"นกบินได้","lv":"A1","cat":"pos","note":"'A' เป็น article (คำนำหน้านาม) วางหน้า noun 'bird'. ใช้ 'a' กับนามนับได้เอกพจน์."},
  {"en":"They walk slowly.","th":"พวกเขาเดินช้าๆ","lv":"A1","cat":"pos","note":"'slowly' เป็น adverb ขยาย verb 'walk' บอกว่าทำอย่างไร. adverb มักลงท้าย -ly."},
  {"en":"The book is big.","th":"หนังสือเล่มนี้ใหญ่","lv":"A1","cat":"pos","note":"'big' เป็น adjective ขยาย noun 'book' บอกขนาด. 'is' เป็น verb เชื่อมประธานกับคุณศัพท์."},
  {"en":"You and I win.","th":"คุณกับฉันชนะ","lv":"A1","cat":"pos","note":"'and' เป็น conjunction เชื่อม pronoun 'You' กับ 'I'. 'win' เป็น verb."},
  {"en":"My sister loves music.","th":"น้องสาวของฉันรักเสียงดนตรี","lv":"A2","cat":"pos","note":"'sister' และ 'music' เป็น noun. 'My' เป็น determiner บอกความเป็นเจ้าของ."},
  {"en":"The boy ran very quickly.","th":"เด็กชายวิ่งเร็วมาก","lv":"A2","cat":"pos","note":"'quickly' เป็น adverb ขยาย verb 'ran'. 'very' เป็น adverb ขยาย adverb อีกที."},
  {"en":"This happy dog wags its tail.","th":"สุนัขที่มีความสุขตัวนี้กระดิกหาง","lv":"A2","cat":"pos","note":"'happy' เป็น adjective ขยาย noun 'dog'. 'This' เป็น determiner ชี้เฉพาะ."},
  {"en":"She put the cup under the table.","th":"เธอวางถ้วยไว้ใต้โต๊ะ","lv":"A2","cat":"pos","note":"'under' เป็น preposition บอกตำแหน่งของถ้วยเทียบกับโต๊ะ."},
  {"en":"He works hard but stays calm.","th":"เขาทำงานหนักแต่ก็ยังใจเย็น","lv":"A2","cat":"pos","note":"'but' เป็น conjunction เชื่อมสองความคิดที่ขัดแย้งกัน."},
  {"en":"We gave them our old books.","th":"เราให้หนังสือเก่าของเราแก่พวกเขา","lv":"A2","cat":"pos","note":"'them' และ 'our' เป็น pronoun/determiner ใช้แทนและบอกความเป็นเจ้าของ."},
  {"en":"The teacher speaks loudly today.","th":"คุณครูพูดเสียงดังวันนี้","lv":"A2","cat":"pos","note":"'loudly' เป็น adverb ขยาย verb 'speaks' บอกลักษณะการพูด. 'The' เป็น article."},
  {"en":"A small child opened the door.","th":"เด็กตัวเล็กเปิดประตู","lv":"A2","cat":"pos","note":"'opened' เป็น verb บอกการกระทำในอดีต. 'small' เป็น adjective ขยาย 'child'."},
  {"en":"I left my keys at home.","th":"ฉันลืมกุญแจไว้ที่บ้าน","lv":"A2","cat":"pos","note":"'at' เป็น preposition บอกสถานที่. 'my' เป็น determiner บอกความเป็นเจ้าของ."},
  {"en":"Mom and Dad cook dinner together.","th":"แม่กับพ่อทำอาหารเย็นด้วยกัน","lv":"A2","cat":"pos","note":"'and' เป็น conjunction เชื่อมประธานสองคน. 'cook' เป็น verb."},
  {"en":"The students answered every question correctly.","th":"นักเรียนตอบทุกคำถามได้ถูกต้อง","lv":"B1","cat":"pos","note":"'correctly' เป็น adverb ขยาย verb 'answered'. 'every' เป็น determiner บอกปริมาณ."},
  {"en":"Honesty is the most important quality.","th":"ความซื่อสัตย์เป็นคุณสมบัติที่สำคัญที่สุด","lv":"B1","cat":"pos","note":"'Honesty' และ 'quality' เป็น noun แบบนามธรรม. 'important' เป็น adjective."},
  {"en":"He suddenly realized his serious mistake.","th":"เขารู้ตัวขึ้นมาทันทีถึงความผิดพลาดร้ายแรง","lv":"B1","cat":"pos","note":"'realized' เป็น verb บอกการกระทำทางความคิด. 'suddenly' เป็น adverb ขยายกริยา."},
  {"en":"The cat hid behind the wooden fence.","th":"แมวซ่อนตัวอยู่หลังรั้วไม้","lv":"B1","cat":"pos","note":"'behind' เป็น preposition บอกตำแหน่ง. 'wooden' เป็น adjective ขยาย 'fence'."},
  {"en":"She studied because she wanted success.","th":"เธอตั้งใจเรียนเพราะเธอต้องการความสำเร็จ","lv":"B1","cat":"pos","note":"'because' เป็น conjunction เชื่อมประโยคโดยบอกเหตุผล."},
  {"en":"Nobody knew where they had gone.","th":"ไม่มีใครรู้ว่าพวกเขาไปไหน","lv":"B1","cat":"pos","note":"'Nobody' และ 'they' เป็น pronoun. 'Nobody' เป็นสรรพนามไม่ชี้เฉพาะ."},
  {"en":"The bright sun shone over the calm sea.","th":"ดวงอาทิตย์ที่สว่างจ้าส่องแสงเหนือทะเลที่สงบ","lv":"B1","cat":"pos","note":"'bright' และ 'calm' เป็น adjective ขยาย noun. 'over' เป็น preposition."},
  {"en":"This problem requires careful and quick thinking.","th":"ปัญหานี้ต้องใช้การคิดที่รอบคอบและรวดเร็ว","lv":"B1","cat":"pos","note":"'careful' และ 'quick' เป็น adjective เชื่อมด้วย conjunction 'and'."},
  {"en":"My brother carefully painted the entire wall.","th":"พี่ชายของฉันทาสีกำแพงทั้งหมดอย่างระมัดระวัง","lv":"B1","cat":"pos","note":"'carefully' เป็น adverb ขยาย verb 'painted'. 'entire' เป็น determiner/adjective."},
  {"en":"The river flows gently through the green valley.","th":"แม่น้ำไหลเอื่อยผ่านหุบเขาสีเขียว","lv":"B1","cat":"pos","note":"'through' เป็น preposition บอกการเคลื่อนที่ผ่าน. 'gently' เป็น adverb."},
  {"en":"Several curious tourists photographed the ancient stone temple.","th":"นักท่องเที่ยวที่อยากรู้อยากเห็นหลายคนถ่ายรูปวัดหินโบราณ","lv":"B2","cat":"pos","note":"'tourists' และ 'temple' เป็น noun. 'Several' เป็น determiner บอกจำนวน."},
  {"en":"The committee will carefully review your detailed proposal.","th":"คณะกรรมการจะพิจารณาข้อเสนอที่ละเอียดของคุณอย่างรอบคอบ","lv":"B2","cat":"pos","note":"'review' เป็น verb. 'carefully' เป็น adverb ขยายกริยานี้บอกลักษณะการกระทำ."},
  {"en":"An extremely talented musician performed a beautiful song.","th":"นักดนตรีที่มีพรสวรรค์อย่างยิ่งบรรเลงเพลงที่ไพเราะ","lv":"B2","cat":"pos","note":"'talented' และ 'beautiful' เป็น adjective. 'extremely' เป็น adverb ขยาย adjective."},
  {"en":"She quietly slipped between the crowded market stalls.","th":"เธอลอดผ่านแผงตลาดที่แออัดไปอย่างเงียบๆ","lv":"B2","cat":"pos","note":"'between' เป็น preposition บอกตำแหน่งระหว่างสิ่งของ. 'quietly' เป็น adverb."},
  {"en":"Although it rained heavily, we still enjoyed ourselves.","th":"ถึงแม้ฝนจะตกหนัก เราก็ยังสนุกกัน","lv":"B2","cat":"pos","note":"'Although' เป็น conjunction เชื่อมประโยคแบบบอกการขัดแย้ง/ยอมรับ."},
  {"en":"Whoever finishes first should help everyone else.","th":"ใครก็ตามที่ทำเสร็จก่อนควรช่วยคนอื่นๆ ทุกคน","lv":"B2","cat":"pos","note":"'Whoever' และ 'everyone' เป็น pronoun. 'Whoever' เป็นสรรพนามไม่ชี้เฉพาะ."},
  {"en":"The exhausted runner finally collapsed near the bright finish.","th":"นักวิ่งที่เหนื่อยล้าทรุดลงในที่สุดใกล้เส้นชัยที่สว่างจ้า","lv":"B2","cat":"pos","note":"'finally' เป็น adverb ขยาย verb 'collapsed' บอกลำดับ. 'near' เป็น preposition."},
  {"en":"Both managers agreed, yet neither signed the contract.","th":"ผู้จัดการทั้งสองเห็นด้วย แต่ก็ไม่มีใครเซ็นสัญญา","lv":"B2","cat":"pos","note":"'yet' เป็น conjunction เชื่อมแบบขัดแย้ง. 'neither' เป็น pronoun/determiner."},
  {"en":"Modern technology constantly changes how people communicate worldwide.","th":"เทคโนโลยีสมัยใหม่เปลี่ยนวิธีที่ผู้คนสื่อสารกันทั่วโลกอยู่ตลอดเวลา","lv":"B2","cat":"pos","note":"'changes' และ 'communicate' เป็น verb. 'constantly' เป็น adverb ขยายกริยา."},
  {"en":"The wise old leader spoke with surprising gentleness.","th":"ผู้นำที่ชราและฉลาดพูดด้วยความอ่อนโยนอย่างน่าประหลาดใจ","lv":"B2","cat":"pos","note":"'wise' และ 'old' เป็น adjective ขยาย noun 'leader'. 'with' เป็น preposition."},
  // ── ประเภทประโยค (stype) ──
  {"en":"I like coffee.","th":"ฉันชอบกาแฟ","lv":"A1","cat":"stype","note":"ประโยคบอกเล่า (statement) โครงสร้าง ประธาน + กริยา + กรรม. 'I like coffee' present simple"},
  {"en":"She is my friend.","th":"เธอเป็นเพื่อนของฉัน","lv":"A1","cat":"stype","note":"ประโยคบอกเล่า (statement) ใช้ verb to be 'is' เชื่อมประธานกับส่วนขยาย"},
  {"en":"We are very happy.","th":"พวกเรามีความสุขมาก","lv":"A1","cat":"stype","note":"ประโยคบอกเล่า (statement) ใช้ 'are' กับประธานพหูพจน์ 'we' ตามด้วยคำคุณศัพท์"},
  {"en":"Do you like tea?","th":"คุณชอบชาไหม","lv":"A1","cat":"stype","note":"คำถาม yes/no: Do + ประธาน + กริยา. ใช้ do ช่วยใน present simple จบด้วย ?"},
  {"en":"What is your name?","th":"คุณชื่ออะไร","lv":"A1","cat":"stype","note":"wh-question: What + is + ประธาน. ถามชื่อด้วย verb to be จบด้วย ?"},
  {"en":"Where do you live?","th":"คุณอยู่ที่ไหน","lv":"A1","cat":"stype","note":"wh-question: Where + do + ประธาน + กริยา. ใช้ do ช่วยใน present simple"},
  {"en":"Please open the window.","th":"กรุณาเปิดหน้าต่าง","lv":"A1","cat":"stype","note":"ประโยคคำสั่ง (imperative) ขึ้นต้นด้วยกริยา 'open' ไม่มีประธาน. เติม 'please' ให้สุภาพ"},
  {"en":"I do not know.","th":"ฉันไม่รู้","lv":"A1","cat":"stype","note":"ประโยคปฏิเสธ (negative) ใช้ 'do not' + กริยา. do ช่วยทำให้เป็นปฏิเสธ"},
  {"en":"He is not here.","th":"เขาไม่ได้อยู่ที่นี่","lv":"A1","cat":"stype","note":"ประโยคปฏิเสธ (negative) ใช้ verb to be 'is' + not"},
  {"en":"Close the door now.","th":"ปิดประตูเดี๋ยวนี้","lv":"A1","cat":"stype","note":"ประโยคคำสั่ง (imperative) ขึ้นต้นด้วยกริยา 'close' ไม่มีประธาน"},
  {"en":"My brother works at home.","th":"พี่ชายของฉันทำงานที่บ้าน","lv":"A2","cat":"stype","note":"ประโยคบอกเล่า (statement) ประธานเอกพจน์ 'brother' กริยาเติม -s เป็น 'works'"},
  {"en":"They are watching a movie.","th":"พวกเขากำลังดูหนัง","lv":"A2","cat":"stype","note":"ประโยคบอกเล่า (statement) present continuous: are + watching แสดงการกระทำขณะนี้"},
  {"en":"Does she speak English well?","th":"เธอพูดภาษาอังกฤษเก่งไหม","lv":"A2","cat":"stype","note":"คำถาม yes/no: Does + ประธาน + กริยา. ใช้ does กับประธานเอกพจน์ present simple"},
  {"en":"When does the bus leave?","th":"รถบัสออกเมื่อไหร่","lv":"A2","cat":"stype","note":"wh-question: When + does + ประธาน + กริยา. ใช้ does ช่วยกับประธานเอกพจน์"},
  {"en":"Who is that tall man?","th":"ผู้ชายสูงคนนั้นคือใคร","lv":"A2","cat":"stype","note":"wh-question: Who + is + ส่วนขยาย. ใช้ verb to be ถามตัวบุคคล"},
  {"en":"Why are you so tired?","th":"ทำไมคุณถึงเหนื่อยจัง","lv":"A2","cat":"stype","note":"wh-question: Why + are + ประธาน + คำคุณศัพท์. ถามเหตุผลด้วย verb to be"},
  {"en":"Don't forget your keys.","th":"อย่าลืมกุญแจของคุณ","lv":"A2","cat":"stype","note":"ประโยคคำสั่งปฏิเสธ (negative imperative) ใช้ Don't + กริยา ห้ามทำสิ่งใด"},
  {"en":"We did not see them.","th":"พวกเราไม่ได้เห็นพวกเขา","lv":"A2","cat":"stype","note":"ประโยคปฏิเสธ (negative) past simple: did not + กริยาช่อง 1 'see'"},
  {"en":"She doesn't eat meat.","th":"เธอไม่กินเนื้อสัตว์","lv":"A2","cat":"stype","note":"ประโยคปฏิเสธ (negative) present simple: doesn't + กริยา กับประธานเอกพจน์"},
  {"en":"Turn off the lights please.","th":"ช่วยปิดไฟด้วย","lv":"A2","cat":"stype","note":"ประโยคคำสั่ง (imperative) phrasal verb 'turn off' ไม่มีประธาน เติม please สุภาพ"},
  {"en":"My sister has lived here for years.","th":"พี่สาวของฉันอาศัยอยู่ที่นี่มาหลายปี","lv":"B1","cat":"stype","note":"ประโยคบอกเล่า (statement) present perfect: has + lived แสดงเหตุการณ์ต่อเนื่องถึงปัจจุบัน"},
  {"en":"They were playing football yesterday afternoon.","th":"พวกเขาเล่นฟุตบอลกันเมื่อบ่ายวานนี้","lv":"B1","cat":"stype","note":"ประโยคบอกเล่า (statement) past continuous: were + playing แสดงการกระทำต่อเนื่องในอดีต"},
  {"en":"Have you finished your homework yet?","th":"คุณทำการบ้านเสร็จหรือยัง","lv":"B1","cat":"stype","note":"คำถาม yes/no: Have + ประธาน + กริยาช่อง 3. present perfect ถามว่าทำเสร็จหรือยัง"},
  {"en":"How did you learn to cook?","th":"คุณเรียนทำอาหารได้ยังไง","lv":"B1","cat":"stype","note":"wh-question: How + did + ประธาน + กริยา. ใช้ did ช่วยใน past simple"},
  {"en":"Which book did you enjoy most?","th":"คุณชอบหนังสือเล่มไหนมากที่สุด","lv":"B1","cat":"stype","note":"wh-question: Which + คำนาม + did + ประธาน + กริยา. ถามตัวเลือกใน past simple"},
  {"en":"Could you help me with this?","th":"คุณช่วยฉันทำสิ่งนี้ได้ไหม","lv":"B1","cat":"stype","note":"คำขอร้องสุภาพ (polite request) ใช้ Could you + กริยา ขอความช่วยเหลืออย่างนุ่มนวล"},
  {"en":"He hasn't called me since Monday.","th":"เขาไม่ได้โทรหาฉันเลยตั้งแต่วันจันทร์","lv":"B1","cat":"stype","note":"ประโยคปฏิเสธ (negative) present perfect: hasn't + called กับ since บอกจุดเริ่มเวลา"},
  {"en":"Let's go to the beach together.","th":"ไปทะเลกันเถอะ","lv":"B1","cat":"stype","note":"ประโยคชักชวน (imperative) ใช้ Let's + กริยา เสนอให้ทำร่วมกัน"},
  {"en":"Remember to lock the back door.","th":"อย่าลืมล็อกประตูหลังด้วยนะ","lv":"B1","cat":"stype","note":"ประโยคคำสั่ง (imperative) ขึ้นต้นด้วยกริยา 'remember' ตามด้วย to + กริยา"},
  {"en":"I won't go without you.","th":"ฉันจะไม่ไปถ้าไม่มีคุณ","lv":"B1","cat":"stype","note":"ประโยคปฏิเสธ (negative) future: won't (will not) + กริยา แสดงการตัดสินใจในอนาคต"},
  {"en":"The students have been studying since morning.","th":"นักเรียนเรียนหนังสือกันมาตั้งแต่เช้า","lv":"B2","cat":"stype","note":"ประโยคบอกเล่า (statement) present perfect continuous: have been + studying แสดงการกระทำต่อเนื่องถึงปัจจุบัน"},
  {"en":"This bridge was built many years ago.","th":"สะพานนี้ถูกสร้างขึ้นเมื่อหลายปีก่อน","lv":"B2","cat":"stype","note":"ประโยคบอกเล่ารูป passive: was + built กรรมเป็นประธาน เน้นสิ่งที่ถูกกระทำ"},
  {"en":"Would you mind closing that window?","th":"คุณช่วยปิดหน้าต่างบานนั้นหน่อยได้ไหม","lv":"B2","cat":"stype","note":"คำขอร้องสุภาพ (polite request) Would you mind + กริยา-ing ขอร้องอย่างสุภาพมาก"},
  {"en":"How long have you known each other?","th":"คุณสองคนรู้จักกันมานานแค่ไหนแล้ว","lv":"B2","cat":"stype","note":"wh-question: How long + have + ประธาน + known. present perfect ถามระยะเวลา"},
  {"en":"What would you do in my situation?","th":"ถ้าเป็นคุณจะทำยังไงในสถานการณ์ของฉัน","lv":"B2","cat":"stype","note":"wh-question แบบสมมติ: What + would + ประธาน + กริยา. ใช้ would แสดงเงื่อนไขสมมติ"},
  {"en":"Hasn't she already paid the bill?","th":"เธอจ่ายบิลไปแล้วไม่ใช่เหรอ","lv":"B2","cat":"stype","note":"คำถามปฏิเสธ (negative question): Hasn't + ประธาน + กริยาช่อง 3 แสดงความประหลาดใจหรือยืนยัน"},
  {"en":"Please make sure the report is correct.","th":"ช่วยตรวจให้แน่ใจว่ารายงานถูกต้องด้วย","lv":"B2","cat":"stype","note":"ประโยคคำสั่ง (imperative) 'make sure' + อนุประโยค that. สั่งให้ตรวจสอบความถูกต้อง"},
  {"en":"They might not arrive before the meeting.","th":"พวกเขาอาจจะมาไม่ทันก่อนการประชุม","lv":"B2","cat":"stype","note":"ประโยคปฏิเสธ (negative) modal: might not + กริยา แสดงความเป็นไปได้ที่จะไม่เกิด"},
  {"en":"Where were you planning to spend your holiday?","th":"คุณวางแผนจะไปเที่ยววันหยุดที่ไหน","lv":"B2","cat":"stype","note":"wh-question: Where + were + ประธาน + planning. past continuous ถามแผนในอดีต"},
  {"en":"Don't let anyone touch these documents.","th":"อย่าให้ใครมาแตะเอกสารพวกนี้","lv":"B2","cat":"stype","note":"ประโยคคำสั่งปฏิเสธ (negative imperative) Don't let + กรรม + กริยา ห้ามอนุญาตให้ใครทำ"}
];
