// Sentences for the "เรียงประโยค" (word-order) game.
// Vocabulary stays within Oxford 3000. Punctuation is attached to its word.
// Loaded before app.js — exposes the global SENTENCES.
const SENTENCES = [
  // ── A1 — short, everyday (4–6 words) ──────────────────────
  {en:"I go to school every day.", th:"ฉันไปโรงเรียนทุกวัน", lv:"A1"},
  {en:"She likes to eat rice.", th:"เธอชอบกินข้าว", lv:"A1"},
  {en:"We play in the park.", th:"เราเล่นในสวนสาธารณะ", lv:"A1"},
  {en:"He has a big dog.", th:"เขามีหมาตัวใหญ่", lv:"A1"},
  {en:"My mother is at home.", th:"แม่ของฉันอยู่ที่บ้าน", lv:"A1"},
  {en:"They are good friends.", th:"พวกเขาเป็นเพื่อนที่ดี", lv:"A1"},
  {en:"The cat is on the bed.", th:"แมวอยู่บนเตียง", lv:"A1"},
  {en:"I like to read books.", th:"ฉันชอบอ่านหนังสือ", lv:"A1"},
  {en:"We drink water every morning.", th:"เราดื่มน้ำทุกเช้า", lv:"A1"},
  {en:"She has a new car.", th:"เธอมีรถคันใหม่", lv:"A1"},
  {en:"The boy runs very fast.", th:"เด็กผู้ชายวิ่งเร็วมาก", lv:"A1"},
  {en:"My father works in a shop.", th:"พ่อของฉันทำงานในร้าน", lv:"A1"},
  {en:"I want a cup of tea.", th:"ฉันอยากได้ชาสักถ้วย", lv:"A1"},
  {en:"We watch TV at night.", th:"เราดูทีวีตอนกลางคืน", lv:"A1"},
  {en:"The sun is very hot today.", th:"วันนี้แดดร้อนมาก", lv:"A1"},
  {en:"She walks to the bus stop.", th:"เธอเดินไปป้ายรถเมล์", lv:"A1"},
  {en:"He is my best friend.", th:"เขาเป็นเพื่อนสนิทของฉัน", lv:"A1"},
  {en:"I have two brothers.", th:"ฉันมีพี่น้องชายสองคน", lv:"A1"},
  {en:"The baby is sleeping now.", th:"ตอนนี้ทารกกำลังหลับ", lv:"A1"},
  {en:"We go home after school.", th:"เรากลับบ้านหลังเลิกเรียน", lv:"A1"},
  {en:"My sister sings a song.", th:"พี่สาวของฉันร้องเพลง", lv:"A1"},
  {en:"The dog likes to play ball.", th:"หมาชอบเล่นลูกบอล", lv:"A1"},
  {en:"I open the door slowly.", th:"ฉันเปิดประตูช้าๆ", lv:"A1"},
  {en:"She buys fruit at the market.", th:"เธอซื้อผลไม้ที่ตลาด", lv:"A1"},
  {en:"We are happy together.", th:"เรามีความสุขด้วยกัน", lv:"A1"},

  // ── A2 — basic connectors (5–7 words) ─────────────────────
  {en:"I usually wake up at six.", th:"ฉันมักตื่นตอนหกโมง", lv:"A2"},
  {en:"She is learning to drive a car.", th:"เธอกำลังหัดขับรถ", lv:"A2"},
  {en:"We went to the beach last week.", th:"เราไปทะเลเมื่อสัปดาห์ที่แล้ว", lv:"A2"},
  {en:"He wants to become a teacher.", th:"เขาอยากเป็นครู", lv:"A2"},
  {en:"They are watching a film tonight.", th:"คืนนี้พวกเขากำลังจะดูหนัง", lv:"A2"},
  {en:"My friend lives near the river.", th:"เพื่อนของฉันอยู่ใกล้แม่น้ำ", lv:"A2"},
  {en:"I forgot my keys this morning.", th:"เช้านี้ฉันลืมกุญแจ", lv:"A2"},
  {en:"She cooks dinner for her family.", th:"เธอทำอาหารเย็นให้ครอบครัว", lv:"A2"},
  {en:"We need to clean the kitchen.", th:"เราต้องทำความสะอาดครัว", lv:"A2"},
  {en:"He always arrives late for work.", th:"เขามาทำงานสายเสมอ", lv:"A2"},
  {en:"The weather is cold in winter.", th:"อากาศหนาวในฤดูหนาว", lv:"A2"},
  {en:"I would like some more coffee.", th:"ฉันอยากได้กาแฟอีกหน่อย", lv:"A2"},
  {en:"She is afraid of big dogs.", th:"เธอกลัวหมาตัวใหญ่", lv:"A2"},
  {en:"We can meet after the meeting.", th:"เราเจอกันได้หลังประชุม", lv:"A2"},
  {en:"He bought a gift for his mother.", th:"เขาซื้อของขวัญให้แม่", lv:"A2"},
  {en:"They study English every weekend.", th:"พวกเขาเรียนภาษาอังกฤษทุกสุดสัปดาห์", lv:"A2"},
  {en:"My brother plays football with friends.", th:"น้องชายฉันเล่นฟุตบอลกับเพื่อน", lv:"A2"},
  {en:"I will call you later tonight.", th:"ฉันจะโทรหาคุณคืนนี้", lv:"A2"},
  {en:"She does not like spicy food.", th:"เธอไม่ชอบอาหารเผ็ด", lv:"A2"},
  {en:"We waited for the train together.", th:"เรารอรถไฟด้วยกัน", lv:"A2"},
  {en:"He is good at fixing things.", th:"เขาเก่งเรื่องการซ่อมของ", lv:"A2"},
  {en:"The children are drawing pictures.", th:"เด็กๆ กำลังวาดรูป", lv:"A2"},
  {en:"I need to find a new job.", th:"ฉันต้องหางานใหม่", lv:"A2"},
  {en:"She walks her dog in the evening.", th:"เธอพาหมาไปเดินตอนเย็น", lv:"A2"},
  {en:"We often visit our grandparents.", th:"เราไปหาปู่ย่าตายายบ่อยๆ", lv:"A2"},

  // ── B1 — opinions, time clauses (6–8 words) ───────────────
  {en:"I think this book is very interesting.", th:"ฉันคิดว่าหนังสือเล่มนี้น่าสนใจมาก", lv:"B1"},
  {en:"She has lived in London for years.", th:"เธออาศัยอยู่ในลอนดอนมาหลายปี", lv:"B1"},
  {en:"We should leave before it gets dark.", th:"เราควรออกไปก่อนฟ้ามืด", lv:"B1"},
  {en:"He decided to study abroad next year.", th:"เขาตัดสินใจไปเรียนต่างประเทศปีหน้า", lv:"B1"},
  {en:"They are planning a trip to Japan.", th:"พวกเขากำลังวางแผนไปเที่ยวญี่ปุ่น", lv:"B1"},
  {en:"If it rains, we will stay inside.", th:"ถ้าฝนตก เราจะอยู่ข้างใน", lv:"B1"},
  {en:"My teacher explained the lesson very clearly.", th:"ครูของฉันอธิบายบทเรียนได้ชัดเจนมาก", lv:"B1"},
  {en:"She was tired after the long journey.", th:"เธอเหนื่อยหลังจากการเดินทางไกล", lv:"B1"},
  {en:"We have not seen each other recently.", th:"เราไม่ได้เจอกันมาพักหนึ่งแล้ว", lv:"B1"},
  {en:"He promised to help us with the project.", th:"เขาสัญญาว่าจะช่วยเราทำโปรเจกต์", lv:"B1"},
  {en:"The company is looking for new staff.", th:"บริษัทกำลังหาพนักงานใหม่", lv:"B1"},
  {en:"I really enjoy listening to quiet music.", th:"ฉันชอบฟังเพลงเงียบๆ มาก", lv:"B1"},
  {en:"She always tries to do her best.", th:"เธอพยายามทำให้ดีที่สุดเสมอ", lv:"B1"},
  {en:"We discussed the problem during lunch.", th:"เราคุยเรื่องปัญหากันตอนพักเที่ยง", lv:"B1"},
  {en:"He has never been to another country.", th:"เขาไม่เคยไปต่างประเทศเลย", lv:"B1"},
  {en:"They built a small house near the lake.", th:"พวกเขาสร้างบ้านหลังเล็กใกล้ทะเลสาบ", lv:"B1"},
  {en:"I am not sure what to do next.", th:"ฉันไม่แน่ใจว่าจะทำอะไรต่อ", lv:"B1"},
  {en:"She spends most of her time reading.", th:"เธอใช้เวลาส่วนใหญ่ไปกับการอ่าน", lv:"B1"},
  {en:"We learned a lot during the course.", th:"เราเรียนรู้หลายอย่างระหว่างคอร์ส", lv:"B1"},
  {en:"He apologized for being so late.", th:"เขาขอโทษที่มาสายมาก", lv:"B1"},
  {en:"The museum was closed when we arrived.", th:"พิพิธภัณฑ์ปิดตอนที่เราไปถึง", lv:"B1"},
  {en:"I would rather walk than take a taxi.", th:"ฉันอยากเดินมากกว่านั่งแท็กซี่", lv:"B1"},

  // ── B2 — complex, abstract (7–10 words) ───────────────────
  {en:"Although it was raining, we continued the game.", th:"แม้ฝนจะตก เราก็เล่นเกมต่อ", lv:"B2"},
  {en:"The decision will affect everyone in the company.", th:"การตัดสินใจนี้จะส่งผลต่อทุกคนในบริษัท", lv:"B2"},
  {en:"She managed to finish the report on time.", th:"เธอจัดการทำรายงานเสร็จทันเวลา", lv:"B2"},
  {en:"We need to consider all the possible options.", th:"เราต้องพิจารณาทางเลือกที่เป็นไปได้ทั้งหมด", lv:"B2"},
  {en:"He has been working here since last March.", th:"เขาทำงานที่นี่มาตั้งแต่เดือนมีนาคมที่แล้ว", lv:"B2"},
  {en:"The teacher encouraged students to ask more questions.", th:"ครูสนับสนุนให้นักเรียนถามคำถามมากขึ้น", lv:"B2"},
  {en:"Despite the difficulties, they achieved their main goal.", th:"แม้จะลำบาก พวกเขาก็บรรลุเป้าหมายหลัก", lv:"B2"},
  {en:"I had never expected such a kind response.", th:"ฉันไม่เคยคาดคิดว่าจะได้คำตอบที่ใจดีแบบนี้", lv:"B2"},
  {en:"The government introduced a new policy last week.", th:"รัฐบาลออกนโยบายใหม่เมื่อสัปดาห์ที่แล้ว", lv:"B2"},
  {en:"She explained why the experiment had failed.", th:"เธออธิบายว่าทำไมการทดลองถึงล้มเหลว", lv:"B2"},
  {en:"We could have avoided the mistake with more care.", th:"เราน่าจะเลี่ยงความผิดพลาดได้ถ้าระวังกว่านี้", lv:"B2"},
  {en:"His argument was based on solid evidence.", th:"ข้อโต้แย้งของเขาตั้งอยู่บนหลักฐานที่หนักแน่น", lv:"B2"},
  {en:"They are committed to protecting the environment.", th:"พวกเขามุ่งมั่นที่จะปกป้องสิ่งแวดล้อม", lv:"B2"},
  {en:"The project succeeded because of careful planning.", th:"โปรเจกต์สำเร็จเพราะการวางแผนอย่างรอบคอบ", lv:"B2"},
  {en:"I appreciate everything you have done for me.", th:"ฉันซาบซึ้งในทุกสิ่งที่คุณทำเพื่อฉัน", lv:"B2"},
  {en:"She was determined to overcome every challenge.", th:"เธอมุ่งมั่นที่จะเอาชนะทุกอุปสรรค", lv:"B2"},
  {en:"The results suggest that further research is needed.", th:"ผลลัพธ์บ่งชี้ว่าจำเป็นต้องวิจัยเพิ่มเติม", lv:"B2"},
  {en:"We must respect the opinions of other people.", th:"เราต้องเคารพความคิดเห็นของคนอื่น", lv:"B2"}
];
